# Generated by Django 5.0 on 2024-02-15 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('my_unique_admin', '0002_delete_adminprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=50)),
                ('count', models.IntegerField(default=50)),
                ('expiry_date', models.DateField(default=datetime.datetime(2024, 3, 16, 15, 41, 23, 816126))),
                ('min_order', models.DecimalField(decimal_places=2, max_digits=6)),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
