# Generated by Django 5.0 on 2024-02-16 14:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_unique_admin', '0005_alter_coupon_expiry_date_appliedcoupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 17, 20, 9, 44, 135210)),
        ),
    ]
