# Generated by Django 5.0 on 2024-01-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_brand_productvarient_is_holded_products_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvarient',
            name='is_holded',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
