# Generated by Django 5.0 on 2024-02-17 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_products_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvarient',
            name='offer_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='productvarient',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='productvarient',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
