# Generated by Django 5.0 on 2024-02-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_productvarient_offer_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvarient',
            name='offer_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
