# Generated by Django 5.0 on 2024-02-29 04:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransactions',
            name='transaction_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
