# Generated by Django 5.0 on 2024-01-25 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_unique_admin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminProfile',
        ),
    ]
