# Generated by Django 5.0 on 2024-02-15 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_order_delivery_address_orderaddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderAddress',
        ),
    ]
