# Generated by Django 5.0 on 2024-02-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_wallet_last_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='actual_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='return_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
