# Generated by Django 5.0 on 2024-02-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_delete_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reerral_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
