# Generated by Django 5.0 on 2024-02-29 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_user_reerral_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='reerral_code',
            new_name='referral_code',
        ),
    ]
