# Generated by Django 5.0 on 2024-02-15 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_delete_orderaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(default='Kerala', max_length=50)),
                ('landmark', models.CharField(max_length=50, null=True)),
                ('pin', models.BigIntegerField()),
                ('address_line', models.TextField(null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='user.order')),
            ],
        ),
    ]
