# Generated by Django 5.0 on 2024-02-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_orderaddress_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='return_status',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
