# Generated by Django 5.0 on 2024-02-27 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_order_actual_price_alter_order_return_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
