# Generated by Django 5.0 on 2024-01-31 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_products_brand_alter_products_sub_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.products'),
        ),
    ]
