# Generated by Django 5.0 on 2024-02-16 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
        ('products', '0007_alter_products_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='offer.offer'),
        ),
    ]
