# Generated by Django 5.0 on 2024-03-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_category_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit',
            field=models.CharField(max_length=5),
        ),
    ]
